language: node_js
node_js:
    - 12
cache: yarn
addons:
    sonarcloud:
        organization: maroben
        token:
            secure: ozyUpfwTMrAqdZQv4BoCjvrs7aWqu/1fvq+ADAVQgSaRqN6Rlf6PVhmC+B8fvbgfPWX95txfYnpKS9kEscmu71lZ1A/eJJdnCI0gjJskiNpaUd1+8Joce1h74fa9jud7UWybGv/UdR8lROmrFp46k31Ghcls/Mu9vR7B8QIyDnFF6p4E0KhExCnuU8I57Etz0UkQSMP2gzzEUYZswSrn30hqo4B5usTEuBriaIRV8X0y/FPMJ3DDVOwLq074WOecdM29K+2IF/BGtpyW4Wy6fuvuK52RwAwnmSA4ZhuZFF5xaW10ttwIt9GDtyA3NIzEUKciqSFwg7xOYpQwuTEp0sCVXX7beUoOCKyDnyjqDNcQjzpFqB69/n9OdFWm9h7pomSUeGS4fxoaE5TImsi8e58vubPGs6f/pY3TVSvOYGK4ZS0sXnOGuKOl4ItS+1kxf1rQEQi6eOL9TPdxvr9jdp7MO9PUKSoJzACAv1Q4QrYJpX5D/RO+E2Qu/Gnre4T53LqTQrV6FhugIuH9RX2+RBWRZZN75liCv2spH12Q36jICwGBRnirYyuP4w2f7nK38oMOx9vSCdj9/XQCH3pLC4AtwS/bGM7y6a8qLtKfOOofm1vINOnwmQz2CnwmksZdMKpq0nz4Lni6EZOgm8tKtNcpHmYBCcXaaAFLCscbX1U=
before_install:
    - export TZ=Europe/Zurich
install: yarn
script:
    - yarn build
    - sonar-scanner
deploy:
    provider: firebase
    project: tichu-counter
    token:
        secure: U2TAgn0aqXCWF/cuZ9IbPMGatQMh6BJ4GE+pxhmGmiSS3TFyeNU3uYVXXmMI7brPpcobuMmSiQQClViA9NqX6GPZcdh+IVw5t7Bju9G/fUhUlHZqALer0ckArca1D5/CcaWSOQ3R86+6iXHA0fr3PYKx14WRbiGc3rynut73IT5JiIqBXI0GgYgF3+jUnNkezhEb89oGC2tFQKaY3mUwjA6JR3Jndwkq1qOc2dybCnj+uSnZulwpfFmCkFmbMVvvlEK2WGysTNOAro8VhEfPaJWK+GiSruy94+4M1PWdmnn+v4bDkI6/q+1upUxtITNaO3ydkctqPIJ4B3S7sDJsleVbSTrlylqzPrUgmaMvp0EYbHIARwQJ7PJRjSIVAgWApythU3IGlqcwJZicVha/hB3aNsYJVXXwoGZvqQf6ZlVUA57bjvtxWI+Ke3tHBhdRAH85mogirOLFzBA8Bv0JQe9qLhX/y/1PxGdxkAibIyt7BMM+icPWF2B2YemAT1qObEXiQMmQUFqwQB9NvVeR67DtFCyGWlTUWV3ZZC4KFsEGKjsyw+dKJXFKOYrsW6twaTXg24WwzWJIzCUZEU4NWZ/SxcD+3Jelt5amB9zutFX2PdGKjwa109aCoSRLipr4NuRbq0MjpFeA5sTvq3ysyUQM/0mFBoygAT0NeJFaHoM=
