language: node_js
node_js:
    - 12
cache: yarn
addons:
    sonarcloud:
        organization: maroben
        token:
            secure: J21vW4fo8uYB81XJHYp5e0r7iZMG/T4pUm7gGcBiVeDo+VflDmmbtO0CFgsnqfElw5YsMKx2yISrdV+NkgAGVxyE/ekDwkM12YOj1u0DN9jAgA/T+VE5KiwXWhN1CjKU0lJKHZctef1m5fOShoVG5dMinzgRpYNqRmfg4VfpEYk0bxX5AS2FiykQoXXiPnBNbu5jLiiOzg2DowgIqIoxwGXs+wcTi3lkbEsN5Z10l3fpWjSNuIFYzacqAisQzN0qqk3X7ZV2OTZcyMr3/JET/KBLAErB5o/mEeyqJu16chkyOBu+6ybyPdWvFtQUMVJDDAvX0fW1RguHynoKf/vZdIINI5LVbEaruorIOzET2PEDUO8n9VApg6EtPK8CW6Nhb/Hmfz5uXpv3OxdiJ2gjEZ5qP2/8nG1o0NSWFNHy4w8rj0kHJvXPFxCi1x9kyenhIex4Za6XEdpNKVr6a5OFQ1KzwiGSYuCsIijC6FVmS3pJvdAwNc+9QBAPjKiAMsDQbNs/jrGW2uAPVfsvJq+mF6yZ1EDXclWbE4zmIDiDgxqp/tA43SY0uFlwlDWbxZG15ysNjCXup/1JYqYS8fPUaxVzIcFZl2k/q0LHINKbz4snTmp1+QUzqgRQXmKms0Q9yFQD3YJVJaJzzVaDgJgSpW3NWCH1JPD7h1DdQGMcr94=
before_install:
    - export TZ=Europe/Zurich
install: yarn
script:
    - yarn build
    - sonar-scanner
deploy:
    provider: firebase
    project: tichu-counter
    token:
        secure: ZHqyQ+6B+7n6rO+awSnf6y1WwmZGw34mrtCz5MFmHWwisYM5AATSmn56BFbce3ITuEOFaO6FZfAwYsjPn14Fh+MJPJjcFSKtkRZ+MQXCzc0bCLgLP2xf1XXVYD6Lnk/D+5pVDWj93JWYANW7l7lc2IjoYfcirpC42k+mRH4za0S4AmiRfoq8EGQWa44N0ln0jJEqTd/GQ97W9ViR6B5b2I72/fAjCgmgEJofC4ME7BklwDW1ZRqeLmm0YSXRim8uuPuzgLp3PcaJpIQpRhrygq1/dBfdIFFXpnPl8C9xfYjOyPHSVqhny+rdcb7c+UcvdzXM3LZwa1BGkq2ugCyCxNfAnyarJDQcjBKjMxBW6/lbyxAsAOMrQwuBHki7mSPRjYWgnbMV7++sSCDwdtOMahxON95B6UxrNGvjee0OFLnBEA+fnl3dGCfq3128bQc/e+qAIQQceE+36BwOwgn1nSKk9g1nQotJYlQDJlmsDhMt4gEDLZjZMLSES8aHOXomdAD1xRSz26eY8F/1HSzxGMiLQegvND7kGRNzh5yKeJ9550/6WBnx4fpb0a4eS8ve4420xa/4DL6f22YUnqnX00iby4P6PLvLmtoJyjUOzRvQIclL/9ii6eQCBAH5VCNcV0c4UczSDD2c8RTCB/plIu3qiabplOb2YFfPC2tdN6U=
